In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("aggregate_population_data.csv")

In [6]:
df

,Entity,Code,Year,Population (historical estimates),"Fertility rate (Complete Gapminder, v12) (2017)",Life expectancy,"Mortality rate, infant (per 1,000 live births)",Human Development Index (UNDP),"Average Total Years of Schooling for Adult Population (Lee-Lee (2016), Barro-Lee (2018) and UNDP (2018))","Estimates, 1950 - 2020: Annually interpolated demographic indicators - Population change (thousands)","Medium fertility variant, 2020 - 2099: Annually interpolated demographic indicators - Population change (thousands)",Sex ratio at birth (Chao et al. 2019)
0,Afghanistan,AFG,1800,3280000,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,1801,3280000,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,1802,3280000,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,1803,3280000,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,1804,3280000,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
46811,Zimbabwe,ZWE,2017,14236599,3.68,60.812,4.05,0.535,8.2,204257.0,NaN,102.333534
46812,Zimbabwe,ZWE,2018,14438812,NaN,61.195,3.93,NaN,NaN,204426.0,NaN,NaN
46813,Zimbabwe,ZWE,2019,14645473,NaN,61.490,3.84,NaN,NaN,212024.0,NaN,NaN
46814,Zimbabwe,ZWE,2020,14862927,NaN,NaN,NaN,NaN,NaN,NaN,223311.0,NaN
46815,Zimbabwe,ZWE,2021,15092171,NaN,NaN,NaN,NaN,NaN,NaN,234218.0,NaN

In [7]:
df2 = df[df['Entity'] == "World"]

In [8]:
df2

Empty DataFrame
Columns: [Entity, Code, Year, Population (historical estimates), Fertility rate (Complete Gapminder, v12) (2017), Life expectancy, Mortality rate, infant (per 1,000 live births), Human Development Index (UNDP), Average Total Years of Schooling for Adult Population (Lee-Lee (2016), Barro-Lee (2018) and UNDP (2018)), Estimates, 1950 - 2020: Annually interpolated demographic indicators - Population change (thousands), Medium fertility variant, 2020 - 2099: Annually interpolated demographic indicators - Population change (thousands), Sex ratio at birth (Chao et al. 2019)]
Index: []

In [11]:
df3 = pd.read_csv("aggregate_hdi_indicators_with_population.csv")

In [12]:
df3

,Entity,Code,Year,Population (historical estimates),"Fertility rate (Complete Gapminder, v12) (2017)","Mortality rate, infant (per 1,000 live births)",Life expectancy,"Average Total Years of Schooling for Adult Population (Lee-Lee (2016), Barro-Lee (2018) and UNDP (2018))",Expected Years of Schooling (years),"GNI per capita, PPP (constant 2017 international $)",Actual Human Development Index (UNDP)
0,Afghanistan,AFG,1800,3280000.0,7.00,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,1801,3280000.0,7.00,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,1802,3280000.0,7.00,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,1803,3280000.0,7.00,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,1804,3280000.0,7.00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
49729,Zimbabwe,ZWE,2017,14236599.0,3.68,4.05,60.812,8.2,10.3,3207.887558,0.535
49730,Zimbabwe,ZWE,2018,14438812.0,NaN,3.93,61.195,NaN,NaN,3262.224759,NaN
49731,Zimbabwe,ZWE,2019,14645473.0,NaN,3.84,61.490,NaN,NaN,NaN,NaN
49732,Zimbabwe,ZWE,2020,14862927.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49733,Zimbabwe,ZWE,2021,15092171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df4 = df3[df3['Entity'] == "World"]

In [14]:
df4

Empty DataFrame
Columns: [Entity, Code, Year, Population (historical estimates), Fertility rate (Complete Gapminder, v12) (2017), Mortality rate, infant (per 1,000 live births), Life expectancy, Average Total Years of Schooling for Adult Population (Lee-Lee (2016), Barro-Lee (2018) and UNDP (2018)), Expected Years of Schooling (years), GNI per capita, PPP (constant 2017 international $), Actual Human Development Index (UNDP)]
Index: []